// Generated by Python Deploy Script
const CONFIG = {
    ENV: 'PROD',
    API: {
        development: { baseURL: 'http://127.0.0.1:8787' },
        production: { baseURL: 'https://fertig-lance-backend-production.dronov-dmitry-bim.workers.dev' }
    },
    SETTINGS: { maxContactLinks: 10, defaultPageSize: 20, retryAttempts: 3, retryDelay: 1000 },
    turnstileSiteKey: '0x4AAAAAACoPG9Z-dUnLl6t1',
    turnstileAllowedHosts: ['localhost', '127.0.0.1', 'dronov-dmitry.github.io'],
    googleClientId: '942439626251-l8k95f346vef0n3igj9gl8q95d2cqki7.apps.googleusercontent.com',
    googleAllowedHosts: ['localhost', '127.0.0.1', 'dronov-dmitry.github.io'],
    specializations: [
        'Web Development',
        'Mobile Development',
        'Software Development',
        'Data Science & Analytics',
        'Design & Creative',
        'Writing & Translation',
        'Marketing & Sales',
        'Admin Support',
        'Video Edit',
        'Customer Service',
        'Engineering & Architecture',
        'IT & Networking',
        'Legal',
        'Management',
        'Other'
    ]
};
function getRuntimeEnv() {
    const host = window.location.hostname;
    const isLocalHost = host === 'localhost' || host === '127.0.0.1';
    if (isLocalHost) return 'development';

    const env = (CONFIG.ENV || '').toLowerCase();
    if (env === 'production' || env === 'prod') return 'production';
    if (env === 'development' || env === 'dev' || env === 'local') return 'production';

    return 'production';
}
function getConfig() {
    const env = getRuntimeEnv();
    const fallbackURL = env === 'development'
        ? 'http://127.0.0.1:8787'
        : CONFIG.API.production.baseURL;
    const apiConfig = CONFIG.API[env] || { baseURL: fallbackURL };
    return {
        apiBaseURL: apiConfig.baseURL || fallbackURL,
        ...CONFIG.SETTINGS,
        turnstileSiteKey: CONFIG.turnstileSiteKey || '',
        turnstileAllowedHosts: CONFIG.turnstileAllowedHosts || [],
        googleClientId: CONFIG.googleClientId || '',
        googleAllowedHosts: CONFIG.googleAllowedHosts || [],
        specializations: CONFIG.specializations || []
    };
}
window.APP_CONFIG = getConfig();